/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;
import controleur.*;
import modele.*;
/**
 *
 * @author UTI306
 */
public class Interface extends javax.swing.JFrame {

    private Bouchon bouchon;
    /**
     * Creates new form Interface
     */
    public Interface() {
        bouchon = new Bouchon();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Criteres = new javax.swing.JPanel();
        jLabelDateDebut = new javax.swing.JLabel();
        jLabel_DateFin = new javax.swing.JLabel();
        zds_DateDebut = new javax.swing.JTextField();
        zds_DateFin = new javax.swing.JTextField();
        jRadio_Celcius = new javax.swing.JRadioButton();
        jRadio_Fahrenheit = new javax.swing.JRadioButton();
        jCombo_Zone = new javax.swing.JComboBox<>();
        Btn_Ok = new javax.swing.JButton();
        jlabel_Zone = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_LogoVinci = new javax.swing.JLabel();
        jPanel_Alerte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        zds_Min = new javax.swing.JTextField();
        zds_Max = new javax.swing.JTextField();
        jLabel_Rouge = new javax.swing.JLabel();
        jLabel_Vert = new javax.swing.JLabel();
        Btn_ModifyAlerte = new javax.swing.JButton();
        jPanel_Data = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Data = new javax.swing.JTable();
        jlabel_DataMinimum = new javax.swing.JLabel();
        zds_DataMinimum = new javax.swing.JTextField();
        jlabel_DataMoyenne = new javax.swing.JLabel();
        zds_DataMoyenne = new javax.swing.JTextField();
        jlabal_DataMaximum = new javax.swing.JLabel();
        zds_DataMaximum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 600));

        jPanel_Criteres.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Critères"));

        jLabelDateDebut.setText("Date de début : ");

        jLabel_DateFin.setText("Date de fin : ");

        zds_DateFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zds_DateFinActionPerformed(evt);
            }
        });

        jRadio_Celcius.setText("Celcius");

        jRadio_Fahrenheit.setText("Fahrenheit");
        jRadio_Fahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_FahrenheitActionPerformed(evt);
            }
        });

        jCombo_Zone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        for (int i=0;i<bouchon.mesZones.size();i++){
            jCombo_Zone.addItem(bouchon.mesZones.get(i).getId_zone()+" - "+bouchon.mesZones.get(i).getLib_zone());
        }

        Btn_Ok.setText("OK");

        jlabel_Zone.setText("Zone : ");

        jButton1.setText("Reset");

        javax.swing.GroupLayout jPanel_CriteresLayout = new javax.swing.GroupLayout(jPanel_Criteres);
        jPanel_Criteres.setLayout(jPanel_CriteresLayout);
        jPanel_CriteresLayout.setHorizontalGroup(
            jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CriteresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CriteresLayout.createSequentialGroup()
                        .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDateDebut)
                            .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlabel_Zone)
                                .addComponent(jLabel_DateFin)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(zds_DateDebut, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(zds_DateFin)))
                    .addComponent(jCombo_Zone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Ok)
                    .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadio_Celcius)
                        .addComponent(jRadio_Fahrenheit))
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_CriteresLayout.setVerticalGroup(
            jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CriteresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateDebut)
                    .addComponent(zds_DateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadio_Celcius))
                .addGap(4, 4, 4)
                .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DateFin)
                    .addComponent(zds_DateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadio_Fahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_Zone)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel_CriteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombo_Zone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Ok))
                .addGap(21, 21, 21))
        );

        jLabel_LogoVinci.setIcon(new javax.swing.ImageIcon("C:\\Users\\UTI306\\Documents\\NetBeansProjects\\VinciThermoGreen\\img\\vinci.png")); // NOI18N

        jPanel_Alerte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Alerte"));

        jLabel1.setText("Minimum : ");

        jLabel2.setText("Maximum : ");

        zds_Min.setText("0");
        zds_Min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zds_MinActionPerformed(evt);
            }
        });

        zds_Max.setText("20");
        zds_Max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zds_MaxActionPerformed(evt);
            }
        });

        jLabel_Rouge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/rouge.png"))); // NOI18N

        jLabel_Vert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/vert.png"))); // NOI18N

        Btn_ModifyAlerte.setText("Modifier");
        Btn_ModifyAlerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModifyAlerteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_AlerteLayout = new javax.swing.GroupLayout(jPanel_Alerte);
        jPanel_Alerte.setLayout(jPanel_AlerteLayout);
        jPanel_AlerteLayout.setHorizontalGroup(
            jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                .addGroup(jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Rouge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Vert))
                    .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                        .addGroup(jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zds_Min, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Btn_ModifyAlerte))
                                    .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(zds_Max, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_AlerteLayout.setVerticalGroup(
            jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AlerteLayout.createSequentialGroup()
                .addGroup(jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(zds_Min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(zds_Max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Btn_ModifyAlerte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_AlerteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Rouge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Vert, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel_Data.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Donnée relevé"));

        jTable_Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zone", "Date", "Heure", "Température"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Data);

        jlabel_DataMinimum.setText("Minimum : ");

        zds_DataMinimum.setEnabled(false);

        jlabel_DataMoyenne.setText("Moyenne : ");

        zds_DataMoyenne.setEnabled(false);

        jlabal_DataMaximum.setText("Maximum : ");

        zds_DataMaximum.setEnabled(false);

        javax.swing.GroupLayout jPanel_DataLayout = new javax.swing.GroupLayout(jPanel_Data);
        jPanel_Data.setLayout(jPanel_DataLayout);
        jPanel_DataLayout.setHorizontalGroup(
            jPanel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel_DataMinimum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zds_DataMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabel_DataMoyenne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zds_DataMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jlabal_DataMaximum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zds_DataMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel_DataLayout.setVerticalGroup(
            jPanel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_DataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_DataMinimum)
                    .addComponent(zds_DataMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_DataMoyenne)
                    .addComponent(zds_DataMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabal_DataMaximum)
                    .addComponent(zds_DataMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_Criteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_LogoVinci)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel_Alerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Criteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_LogoVinci))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Alerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zds_DateFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zds_DateFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zds_DateFinActionPerformed

    private void jRadio_FahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_FahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_FahrenheitActionPerformed

    private void zds_MinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zds_MinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zds_MinActionPerformed

    private void zds_MaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zds_MaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zds_MaxActionPerformed

    private void Btn_ModifyAlerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModifyAlerteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ModifyAlerteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ModifyAlerte;
    private javax.swing.JButton Btn_Ok;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombo_Zone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDateDebut;
    private javax.swing.JLabel jLabel_DateFin;
    private javax.swing.JLabel jLabel_LogoVinci;
    private javax.swing.JLabel jLabel_Rouge;
    private javax.swing.JLabel jLabel_Vert;
    private javax.swing.JPanel jPanel_Alerte;
    private javax.swing.JPanel jPanel_Criteres;
    private javax.swing.JPanel jPanel_Data;
    private javax.swing.JRadioButton jRadio_Celcius;
    private javax.swing.JRadioButton jRadio_Fahrenheit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Data;
    private javax.swing.JLabel jlabal_DataMaximum;
    private javax.swing.JLabel jlabel_DataMinimum;
    private javax.swing.JLabel jlabel_DataMoyenne;
    private javax.swing.JLabel jlabel_Zone;
    private javax.swing.JTextField zds_DataMaximum;
    private javax.swing.JTextField zds_DataMinimum;
    private javax.swing.JTextField zds_DataMoyenne;
    private javax.swing.JTextField zds_DateDebut;
    private javax.swing.JTextField zds_DateFin;
    private javax.swing.JTextField zds_Max;
    private javax.swing.JTextField zds_Min;
    // End of variables declaration//GEN-END:variables
}
